version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: issue-tracker-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./volumes/mongo:/data/db"
    networks:
      - issue_tracker_network

networks:
  issue_tracker_network:
